apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      slot: blue
      env: production
      app: go-app
  template:
    metadata:
      labels:
        slot: blue
        env: production
        app: go-app
    spec:
      containers:
      - name: blue
        image: luizmandico/blue_green:1.0.0
        env:
          - name: APP_VERSION
            value: "1.0.0"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /go-demo/health
            port: 8888
        ports:
        - name: http
          containerPort: 8888